### ISSUE TITLE
Login without password

### ISSUE THREAD

**Issue by adrez99** [carlonluca/mldonkey-next#2]
I have installed your docker image and am using it without a password because I use the web interface behind nginx proxy secured with authelia. But I can't access mldonkey-next interface without setting a password, the login screen is always shown. Is it possible to disable it?

**Comment by carlonluca** [comment]
Hello, I suspect this is a question for the mldonkey project, isn't it? This repo is just responsible for building and packaging it.

**Comment by adrez99** [comment]
I have no problem with mldonkeys old web interface, it doesn't show any login screen when no password is set. The problem is only on mldonkey-nexts web interface and I think this is the repo, the login page is shown when no password is set but it shouldn't?

**Comment by carlonluca** [comment]
I'm sorry, now I see what you are asking. This is the correct repo, yes.

The login screen does not know this ahead of time, so I'm not sure if this can be done. However, the credentials should be cached the first time, and the autologin procedure should run the following times. Isn't this working for you?

**Comment by adrez99** [comment]
I haven't tried with a password set, but without password, after entering the user it isn't cached and it asks for credentials following times.
I suppose mldonkeys web interface checks if the password is blank in configuration file, and if so, it doesn't show login screen

**Comment by raulfg3** [comment]
same problem here, I use NPM as proxy and i can't pass the login screen, only works on IP:port if use https:myurl and proxy redirect to IP:port do not work
![Captura de pantalla 2024-11-26 213408](https://github.com/user-attachments/assets/9839b7e1-3cd0-4105-b51d-f34083d84fb6)

**Comment by carlonluca** [comment]
> same problem here, I use NPM as proxy and i can't pass the login screen, only works on IP:port if use https:myurl and proxy redirect to IP:port do not work
> ![Captura de pantalla 2024-11-26 213408](https://github.com/user-attachments/assets/9839b7e1-3cd0-4105-b51d-f34083d84fb6)
> 

Is this related to empty password?

**Comment by raulfg3** [comment]
yes and no, in my case I have user & password, but NPM
https://nginxproxymanager.com/ can't pass from the login screen, always the
circle thinking and never pass from this screen.

if I login from http://192.168.1.5:4081 on chrome works fine but that
exactly is the URL used on NPM to redirect and fail.

[image: image.png]

**Comment by carlonluca** [comment]
Then you are probably more in the situation of #11.

**Comment by carlonluca** [comment]
Automatic login should work now with an empty password.

**Comment by raulfg3** [comment]
thanks a lot, I tested when docker image where available.

**Comment by carlonluca** [comment]
The exp tag includes latest commits.
