### ISSUE TITLE
please update geoIP database

### ISSUE THREAD

**Issue by raulfg3** [carlonluca/mldonkey-next#3]
new location for geoIP database Is:

https://mailfud.org/geoip-legacy/GeoIP.dat.gz

need changes in downloads.ini:

line 220, 663

![image](https://github.com/user-attachments/assets/2130c918-039e-462d-8286-bf8213f9b204)

**Comment by raulfg3** [comment]
I do not know, if is the correct place here, but because mldonkey-next is a new reboot, perhaps to correct it, is a good step.

the dedault URL that mldonkey use to download www.maxmind.... is outdated and new one is : https://mailfud.org/geoip-legacy/GeoIP.dat.gz 

I'll thanks to you if where included .

**Comment by carlonluca** [comment]
What I mean is that the url is not part of the client, and mldonkey-next is a client for mldonkey.

**Comment by raulfg3** [comment]
and of course you can close this request.

**Comment by raulfg3** [comment]
resolved: https://github.com/ygrek/mldonkey/issues/119
